### ISSUE TITLE
High level API/CLI for SLEAP integration

### ISSUE THREAD

**Issue by talmo** [talmolab/dreem#45]
Provide equivalents of `sleap-train` and `sleap-track` and an equivalent high-level API for one-call training and inference.

**Comment by talmo** [comment]
Configure it here:

https://github.com/talmolab/biogtr/blob/f0c6f3c12e881b4947ae335d23d334b4fb9d7c89/pyproject.toml#L50-L51

In the current setup, this creates a CLI called `biogtr` which redirects to the `biogtr.cli` module and calls a function within that module named `cli`.

It would be implemented here:

https://github.com/talmolab/biogtr/blob/f0c6f3c12e881b4947ae335d23d334b4fb9d7c89/biogtr/cli.py

Instead, I propose `dreem-train` and `dreem-track` as two explicit CLIs instead of using subcommands.

You can use hydra since we're already set up to do that.

**Comment by aaprasad** [comment]
handled in #61
