### ISSUE TITLE
Update everything to Python 3.11

### ISSUE THREAD

**Issue by talmo** [talmolab/dreem#53]
Future proofing :)

`sleap-io` is already [compatible all the way up to 3.12](https://github.com/talmolab/sleap-io/blob/4af9f38edcd40f5d99f2f93144230aec428f57aa/pyproject.toml).

`sleap-nn` is at [3.9](https://github.com/talmolab/sleap-nn/blob/06f2a6318108e734f0946abdac554bc2c36cf3a9/pyproject.toml) but will be updated.

`pytorch` is already supporting up to [3.11](https://github.com/pytorch/pytorch/blob/4154c8358a757f118b8ee6dbc61f7a2ede10cd15/pyproject.toml#L19).

**Comment by aaprasad** [comment]
handled in #62
