### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by talmo** [talmolab/dreem#54]
- [x] #58
- [x] Example configs/data
- [x] Installation guide: GPU dependencies (what cuda version is required? what pytorch version?), Windows, cluster install, etc.
- [x] Walkthrough/tutorial (like [this](https://github.com/talmolab/sleap-anipose?tab=readme-ov-file#usage))
- [x] API docs (see [`sleap-io`](https://github.com/talmolab/sleap-io/tree/4af9f38edcd40f5d99f2f93144230aec428f57aa/docs) --> https://github.com/talmolab/sleap-io/issues/83)

**Comment by aaprasad** [comment]
Addressend in #55
